import Topnav from "./ui/topnav"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <div>
          <Topnav />
        </div>
        <div>{children}</div>
      </body>
    </html>
  )
}
